name: project_structure
description: "A new Flutter package project that help you to initialize your project structure "
version: 0.0.1
homepage: https://github.com/ahmed3ssem/project_structure

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  get: ^4.6.6
  flutter_bloc: ^8.1.5
  dio: ^5.4.3+1
  get_it: ^7.7.0
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  assets:
    - assets/images/
  fonts:
    - family: Tajawal
      fonts:
         - asset: assets/fonts/Tajawal-Black.ttf
           weight: 900
         - asset: assets/fonts/Tajawal-ExtraBold.ttf
           weight: 800
         - asset: assets/fonts/Tajawal-Bold.ttf
           weight: 700
         - asset: assets/fonts/Tajawal-Medium.ttf
           weight: 500
         - asset: assets/fonts/Tajawal-Regular.ttf
           weight: 400
         - asset: assets/fonts/Tajawal-Light.ttf
           weight: 300
         - asset: assets/fonts/Tajawal-ExtraLight.ttf
           weight: 200
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
